before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
archives:
  -
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
